# Assignment 3
All questions are weighted the same in this assignment. This assignment requires more individual learning then the last one did - you are encouraged to check out the [pandas documentation](http://pandas.pydata.org/pandas-docs/stable/) to find functions or methods you might not have used yet, or ask questions on [Stack Overflow](http://stackoverflow.com/) and tag them as pandas and python related. All questions are worth the same number of points except question 1 which is worth 20% of the assignment grade.

**Note**: Questions 2-13 rely on your question 1 answer.

In [2]:
import pandas as pd
import numpy as np
from IPython.display import display



# Filter all warnings. If you would like to see the warnings, please comment the two lines below.
import warnings
warnings.filterwarnings('ignore')

### Question 1
Load the energy data from the file `assets/Energy Indicators.xls`, which is a list of indicators of [energy supply and renewable electricity production](assets/Energy%20Indicators.xls) from the [United Nations](http://unstats.un.org/unsd/environment/excel_file_tables/2013/Energy%20Indicators.xls) for the year 2013, and should be put into a DataFrame with the variable name of **Energy**.

Keep in mind that this is an Excel file, and not a comma separated values file. Also, make sure to exclude the footer and header information from the datafile. The first two columns are unneccessary, so you should get rid of them, and you should change the column labels so that the columns are:

`['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable]`

Convert `Energy Supply` to gigajoules (**Note: there are 1,000,000 gigajoules in a petajoule**). For all countries which have missing data (e.g. data with "...") make sure this is reflected as `np.NaN` values.

Rename the following list of countries (for use in later questions):

```"Republic of Korea": "South Korea",
"United States of America": "United States",
"United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
"China, Hong Kong Special Administrative Region": "Hong Kong"```

There are also several countries with parenthesis in their name. Be sure to remove these, e.g. `'Bolivia (Plurinational State of)'` should be `'Bolivia'`.

Next, load the GDP data from the file `assets/world_bank.csv`, which is a csv containing countries' GDP from 1960 to 2015 from [World Bank](http://data.worldbank.org/indicator/NY.GDP.MKTP.CD). Call this DataFrame **GDP**. 

Make sure to skip the header, and rename the following list of countries:

```"Korea, Rep.": "South Korea", 
"Iran, Islamic Rep.": "Iran",
"Hong Kong SAR, China": "Hong Kong"```

Finally, load the [Sciamgo Journal and Country Rank data for Energy Engineering and Power Technology](http://www.scimagojr.com/countryrank.php?category=2102) from the file `assets/scimagojr-3.xlsx`, which ranks countries based on their journal contributions in the aforementioned area. Call this DataFrame **ScimEn**.

Join the three datasets: GDP, Energy, and ScimEn into a new dataset (using the intersection of country names). Use only the last 10 years (2006-2015) of GDP data and only the top 15 countries by Scimagojr 'Rank' (Rank 1 through 15). 

The index of this DataFrame should be the name of the country, and the columns should be ['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations',
       'Citations per document', 'H index', 'Energy Supply',
       'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015'].

*This function should return a DataFrame with 20 columns and 15 entries, and the rows of the DataFrame should be sorted by "Rank".*

In [3]:
def answer_one():
    Energy = pd.read_excel("assets/Energy Indicators.xls",usecols='C:F',
                           skiprows=[1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,17],
                          skipfooter=18,
                          names=['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable'])
    
    Energy["Country"] = Energy["Country"].replace("Republic of Korea", "South Korea")
    Energy["Country"] = Energy["Country"].replace("United States of America", "United States")
    Energy["Country"] = Energy["Country"].replace("United Kingdom of Great Britain and Northern Ireland", "United Kingdom")
    Energy["Country"] = Energy["Country"].replace("China, Hong Kong Special Administrative Region", "Hong Kong")
    
    Energy["Energy Supply"] = Energy["Energy Supply"].replace("...",np.NaN)
    Energy["Energy Supply"] = Energy["Energy Supply per Capita"].replace("...",np.NaN)
    Energy["Energy Supply"] = Energy["% Renewable"].replace("...",np.NaN)
    Energy['Country'] = Energy["Country"].replace(r"\(.*?\)", "",regex=True)
    #display(Energy.loc[Energy['Country']=='United States Virgin Islands'])
    #print(Energy.head(50))
    #print(Energy.loc[Energy["Country"]=='South Korea'])
    # YOUR CODE HERE
    GDP = pd.read_csv('assets/world_bank.csv')
    GDP.columns = GDP.iloc[3]
    GDP = GDP.drop(index=[0,1,2,3], axis=0)
    GDP = GDP.reset_index()
    
    #print(GDP.keys())
    GDP["Country Name"] = GDP["Country Name"].replace("Korea, Rep.", "South Korea")
    GDP["Country Name"] = GDP["Country Name"].replace("United States of America", "United States")
    GDP["Country Name"] = GDP["Country Name"].replace("United Kingdom of Great Britain and Northern Ireland", "United Kingdom")
    #display(GDP.keys)
    
    GDP = GDP.rename(columns={"Country Name":"Country"})
    ScimEn = pd.read_excel("assets/scimagojr-3.xlsx")
    
    last10 = GDP[GDP.columns[-10:]]
    last10['Country'] = GDP['Country']
    #display(ScimEn.keys())
    #display(Energy.keys())
    #display(GDP.keys())
    
    Top15 = ScimEn[ScimEn['Rank'] < 16]
    
    #display(Top15)
    #display(last10)
    #display(ScimEn.head())
    #display(Energy.head())
    #display(GDP.head())
    
    TopLat = pd.merge(Top15,last10,how='inner',on='Country')
    TopLat = TopLat.set_index('Country')
    final = pd.merge(TopLat, Energy,how='left',on='Country')
    print('Top15')
    #final = final.set_index('Country')
   # final = 
    display(final)
    #display(final)
    return final
    #display(TopLat)
    #print(Energy.head(-30))
    #raise NotImplementedError()
   
    
answer_one()

Top15

,Country,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,2006.0,2007.0,...,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,Energy Supply,Energy Supply per Capita,% Renewable
0,China,1,127050,126767,597237,411683,4.70,138,3.992331e+12,4.559041e+12,...,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,NaN,NaN,NaN
1,United States,2,96661,94747,792274,265436,8.20,230,1.479230e+13,1.505540e+13,...,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,NaN,NaN,NaN
2,Japan,3,30504,30287,223024,61554,7.31,134,5.496542e+12,5.617036e+12,...,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,NaN,NaN,NaN
3,United Kingdom,4,20944,20357,206091,37874,9.84,139,2.419631e+12,2.482203e+12,...,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,NaN,NaN,NaN
4,Russian Federation,5,18534,18301,34266,12422,1.85,57,1.385793e+12,1.504071e+12,...,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,17.288680,214,17.288680
5,Canada,6,17899,17620,215003,40930,12.01,149,1.564469e+12,1.596740e+12,...,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12,61.945430,296,61.945430
6,Germany,7,17027,16831,140566,27426,8.26,126,3.332891e+12,3.441561e+12,...,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12,17.901530,165,17.901530
7,India,8,15005,14841,128763,37209,8.58,115,1.265894e+12,1.374865e+12,...,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,14.969080,26,14.969080
8,France,9,13153,12973,130632,28601,9.93,114,2.607840e+12,2.669424e+12,...,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12,NaN,NaN,NaN
9,South Korea,10,11983,11923,114675,22595,9.57,104,9.410199e+11,9.924316e+11,...,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12,2.279353,221,2.279353
10,Italy,11,10964,10794,111850,26661,10.20,106,2.202170e+12,2.234627e+12,...,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12,NaN,NaN,NaN
11,Spain,12,9428,9330,123336,23964,13.08,115,1.414823e+12,1.468146e+12,...,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12,NaN,NaN,NaN
12,Australia,14,8831,8725,90765,15606,10.28,107,1.021939e+12,1.060340e+12,...,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12,NaN,NaN,NaN
13,Brazil,15,8668,8596,60702,14396,7.00,86,1.845080e+12,1.957118e+12,...,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,69.648030,59,69.648030

,Country,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,2006.0,2007.0,...,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,Energy Supply,Energy Supply per Capita,% Renewable
0,China,1,127050,126767,597237,411683,4.70,138,3.992331e+12,4.559041e+12,...,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,NaN,NaN,NaN
1,United States,2,96661,94747,792274,265436,8.20,230,1.479230e+13,1.505540e+13,...,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,NaN,NaN,NaN
2,Japan,3,30504,30287,223024,61554,7.31,134,5.496542e+12,5.617036e+12,...,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,NaN,NaN,NaN
3,United Kingdom,4,20944,20357,206091,37874,9.84,139,2.419631e+12,2.482203e+12,...,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,NaN,NaN,NaN
4,Russian Federation,5,18534,18301,34266,12422,1.85,57,1.385793e+12,1.504071e+12,...,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,17.288680,214,17.288680
5,Canada,6,17899,17620,215003,40930,12.01,149,1.564469e+12,1.596740e+12,...,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12,61.945430,296,61.945430
6,Germany,7,17027,16831,140566,27426,8.26,126,3.332891e+12,3.441561e+12,...,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12,17.901530,165,17.901530
7,India,8,15005,14841,128763,37209,8.58,115,1.265894e+12,1.374865e+12,...,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,14.969080,26,14.969080
8,France,9,13153,12973,130632,28601,9.93,114,2.607840e+12,2.669424e+12,...,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12,NaN,NaN,NaN
9,South Korea,10,11983,11923,114675,22595,9.57,104,9.410199e+11,9.924316e+11,...,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12,2.279353,221,2.279353
10,Italy,11,10964,10794,111850,26661,10.20,106,2.202170e+12,2.234627e+12,...,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12,NaN,NaN,NaN
11,Spain,12,9428,9330,123336,23964,13.08,115,1.414823e+12,1.468146e+12,...,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12,NaN,NaN,NaN
12,Australia,14,8831,8725,90765,15606,10.28,107,1.021939e+12,1.060340e+12,...,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12,NaN,NaN,NaN
13,Brazil,15,8668,8596,60702,14396,7.00,86,1.845080e+12,1.957118e+12,...,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,69.648030,59,69.648030

In [6]:
assert type(answer_one()) == pd.DataFrame, "Q1: You should return a DataFrame!"

assert answer_one().shape == (15,20), "Q1: Your DataFrame should have 20 columns and 15 entries!"

AssertionError: Q1: You should return a DataFrame!

In [ ]:
# Cell for autograder.

### Question 2
The previous question joined three datasets then reduced this to just the top 15 entries. When you joined the datasets, but before you reduced this to the top 15 items, how many entries did you lose?

*This function should return a single number.*

In [ ]:
%%HTML
<svg width="800" height="300">
  <circle cx="150" cy="180" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="blue" />
  <circle cx="200" cy="100" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="red" />
  <circle cx="100" cy="100" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="green" />
  <line x1="150" y1="125" x2="300" y2="150" stroke="black" stroke-width="2" fill="black" stroke-dasharray="5,3"/>
  <text x="300" y="165" font-family="Verdana" font-size="35">Everything but this!</text>
</svg>

In [40]:
def answer_two():
    # YOUR CODE HERE
    GDP = pd.read_csv('assets/world_bank.csv')
    print(len(GDP)-15)
    
    #raise NotImplementedError()
answer_two()

253

In [ ]:
assert type(answer_two()) == int, "Q2: You should return an int number!"

### Question 3
What are the top 15 countries for average GDP over the last 10 years?

*This function should return a Series named `avgGDP` with 15 countries and their average GDP sorted in descending order.*

In [58]:
def answer_three():
    # YOUR CODE HERE
    top15 = answer_one()
    display(top15)
    last10 = top15[top15.columns[8:18]]
    mean = last10.mean(axis=1)
    #raise NotImplementedError()
    top15['avgGDP'] = mean
    display(mean)
    return top15
answer_three()

,Rank,Country,Documents,Citable documents,Citations,Self-citations,Citations per document,H index
0,1,China,127050,126767,597237,411683,4.70,138
1,2,United States,96661,94747,792274,265436,8.20,230
2,3,Japan,30504,30287,223024,61554,7.31,134
3,4,United Kingdom,20944,20357,206091,37874,9.84,139
4,5,Russian Federation,18534,18301,34266,12422,1.85,57
5,6,Canada,17899,17620,215003,40930,12.01,149
6,7,Germany,17027,16831,140566,27426,8.26,126
7,8,India,15005,14841,128763,37209,8.58,115
8,9,France,13153,12973,130632,28601,9.93,114
9,10,South Korea,11983,11923,114675,22595,9.57,104
10,11,Italy,10964,10794,111850,26661,10.20,106
11,12,Spain,9428,9330,123336,23964,13.08,115
12,13,Iran,8896,8819,57470,19125,6.46,72
13,14,Australia,8831,8725,90765,15606,10.28,107
14,15,Brazil,8668,8596,60702,14396,7.00,86

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,2006.0,2007.0,2008.0,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0
Country,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2,96661,94747,792274,265436,8.20,230,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3,30504,30287,223024,61554,7.31,134,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,4,20944,20357,206091,37874,9.84,139,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,5,18534,18301,34266,12422,1.85,57,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
Canada,6,17899,17620,215003,40930,12.01,149,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
Germany,7,17027,16831,140566,27426,8.26,126,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
India,8,15005,14841,128763,37209,8.58,115,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
France,9,13153,12973,130632,28601,9.93,114,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
South Korea,10,11983,11923,114675,22595,9.57,104,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12
Italy,11,10964,10794,111850,26661,10.20,106,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
Spain,12,9428,9330,123336,23964,13.08,115,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
Australia,14,8831,8725,90765,15606,10.28,107,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,15,8668,8596,60702,14396,7.00,86,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12

,Country,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,2006.0,2007.0,...,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,Energy Supply,Energy Supply per Capita,% Renewable
0,China,1,127050,126767,597237,411683,4.70,138,3.992331e+12,4.559041e+12,...,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,NaN,NaN,NaN
1,United States,2,96661,94747,792274,265436,8.20,230,1.479230e+13,1.505540e+13,...,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,NaN,NaN,NaN
2,Japan,3,30504,30287,223024,61554,7.31,134,5.496542e+12,5.617036e+12,...,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,NaN,NaN,NaN
3,United Kingdom,4,20944,20357,206091,37874,9.84,139,2.419631e+12,2.482203e+12,...,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,NaN,NaN,NaN
4,Russian Federation,5,18534,18301,34266,12422,1.85,57,1.385793e+12,1.504071e+12,...,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,17.288680,214,17.288680
5,Canada,6,17899,17620,215003,40930,12.01,149,1.564469e+12,1.596740e+12,...,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12,61.945430,296,61.945430
6,Germany,7,17027,16831,140566,27426,8.26,126,3.332891e+12,3.441561e+12,...,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12,17.901530,165,17.901530
7,India,8,15005,14841,128763,37209,8.58,115,1.265894e+12,1.374865e+12,...,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,14.969080,26,14.969080
8,France,9,13153,12973,130632,28601,9.93,114,2.607840e+12,2.669424e+12,...,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12,NaN,NaN,NaN
9,South Korea,10,11983,11923,114675,22595,9.57,104,9.410199e+11,9.924316e+11,...,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12,2.279353,221,2.279353
10,Italy,11,10964,10794,111850,26661,10.20,106,2.202170e+12,2.234627e+12,...,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12,NaN,NaN,NaN
11,Spain,12,9428,9330,123336,23964,13.08,115,1.414823e+12,1.468146e+12,...,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12,NaN,NaN,NaN
12,Australia,14,8831,8725,90765,15606,10.28,107,1.021939e+12,1.060340e+12,...,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12,NaN,NaN,NaN
13,Brazil,15,8668,8596,60702,14396,7.00,86,1.845080e+12,1.957118e+12,...,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,69.648030,59,69.648030

0     6.348609e+12
1     1.536434e+13
2     5.542208e+12
3     2.487907e+12
4     1.565459e+12
5     1.660647e+12
6     3.493025e+12
7     1.769297e+12
8     2.681725e+12
9     1.106715e+12
10    2.120175e+12
11    1.418078e+12
12    1.164043e+12
13    2.189794e+12
dtype: float64

,Country,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,2006.0,2007.0,...,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,Energy Supply,Energy Supply per Capita,% Renewable,avgGDP
0,China,1,127050,126767,597237,411683,4.70,138,3.992331e+12,4.559041e+12,...,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,NaN,NaN,NaN,6.348609e+12
1,United States,2,96661,94747,792274,265436,8.20,230,1.479230e+13,1.505540e+13,...,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,NaN,NaN,NaN,1.536434e+13
2,Japan,3,30504,30287,223024,61554,7.31,134,5.496542e+12,5.617036e+12,...,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,NaN,NaN,NaN,5.542208e+12
3,United Kingdom,4,20944,20357,206091,37874,9.84,139,2.419631e+12,2.482203e+12,...,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,NaN,NaN,NaN,2.487907e+12
4,Russian Federation,5,18534,18301,34266,12422,1.85,57,1.385793e+12,1.504071e+12,...,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,17.288680,214,17.288680,1.565459e+12
5,Canada,6,17899,17620,215003,40930,12.01,149,1.564469e+12,1.596740e+12,...,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12,61.945430,296,61.945430,1.660647e+12
6,Germany,7,17027,16831,140566,27426,8.26,126,3.332891e+12,3.441561e+12,...,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12,17.901530,165,17.901530,3.493025e+12
7,India,8,15005,14841,128763,37209,8.58,115,1.265894e+12,1.374865e+12,...,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,14.969080,26,14.969080,1.769297e+12
8,France,9,13153,12973,130632,28601,9.93,114,2.607840e+12,2.669424e+12,...,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12,NaN,NaN,NaN,2.681725e+12
9,South Korea,10,11983,11923,114675,22595,9.57,104,9.410199e+11,9.924316e+11,...,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12,2.279353,221,2.279353,1.106715e+12
10,Italy,11,10964,10794,111850,26661,10.20,106,2.202170e+12,2.234627e+12,...,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12,NaN,NaN,NaN,2.120175e+12
11,Spain,12,9428,9330,123336,23964,13.08,115,1.414823e+12,1.468146e+12,...,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12,NaN,NaN,NaN,1.418078e+12
12,Australia,14,8831,8725,90765,15606,10.28,107,1.021939e+12,1.060340e+12,...,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12,NaN,NaN,NaN,1.164043e+12
13,Brazil,15,8668,8596,60702,14396,7.00,86,1.845080e+12,1.957118e+12,...,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,69.648030,59,69.648030,2.189794e+12

In [ ]:
assert type(answer_three()) == pd.Series, "Q3: You should return a Series!"

### Question 4
By how much had the GDP changed over the 10 year span for the country with the 6th largest average GDP?

*This function should return a single number.*

In [72]:
def answer_four():
    # YOUR CODE HERE
    top15 = answer_one()
    six = top15.loc[5]
    
    #display(six)
    #display(six[2006.0])
    #print(type(six[2006.0]))
    dif = six[2010.0]-six[2006.0]
    #print('Here')
    #print(dif)
    #raise NotImplementedError()
    return dif
answer_four()

,Rank,Country,Documents,Citable documents,Citations,Self-citations,Citations per document,H index
0,1,China,127050,126767,597237,411683,4.70,138
1,2,United States,96661,94747,792274,265436,8.20,230
2,3,Japan,30504,30287,223024,61554,7.31,134
3,4,United Kingdom,20944,20357,206091,37874,9.84,139
4,5,Russian Federation,18534,18301,34266,12422,1.85,57
5,6,Canada,17899,17620,215003,40930,12.01,149
6,7,Germany,17027,16831,140566,27426,8.26,126
7,8,India,15005,14841,128763,37209,8.58,115
8,9,France,13153,12973,130632,28601,9.93,114
9,10,South Korea,11983,11923,114675,22595,9.57,104
10,11,Italy,10964,10794,111850,26661,10.20,106
11,12,Spain,9428,9330,123336,23964,13.08,115
12,13,Iran,8896,8819,57470,19125,6.46,72
13,14,Australia,8831,8725,90765,15606,10.28,107
14,15,Brazil,8668,8596,60702,14396,7.00,86

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,2006.0,2007.0,2008.0,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0
Country,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2,96661,94747,792274,265436,8.20,230,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3,30504,30287,223024,61554,7.31,134,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,4,20944,20357,206091,37874,9.84,139,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,5,18534,18301,34266,12422,1.85,57,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
Canada,6,17899,17620,215003,40930,12.01,149,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
Germany,7,17027,16831,140566,27426,8.26,126,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
India,8,15005,14841,128763,37209,8.58,115,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
France,9,13153,12973,130632,28601,9.93,114,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
South Korea,10,11983,11923,114675,22595,9.57,104,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12
Italy,11,10964,10794,111850,26661,10.20,106,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
Spain,12,9428,9330,123336,23964,13.08,115,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
Australia,14,8831,8725,90765,15606,10.28,107,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,15,8668,8596,60702,14396,7.00,86,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12

Country                                   Canada
Rank                                           6
Documents                                  17899
Citable documents                          17620
Citations                                 215003
Self-citations                             40930
Citations per document                     12.01
H index                                      149
2006.0                      1564468853329.449951
2007.0                      1596739898466.320068
2008.0                       1612713061250.23999
2009.0                      1565144676082.310059
2010.0                      1613406134731.120117
2011.0                      1664086754804.889893
2012.0                      1693132927878.080078
2013.0                      1730687770724.129883
2014.0                       1773485821199.77002
2015.0                      1792608764608.810059
Energy Supply                           61.94543
Energy Supply per Capita                     296
% Renewable                             61.94543
Name: 5, dtype: object

1564468853329.45

<class 'numpy.float64'>
Here
48937281401.670166

In [ ]:
# Cell for autograder.

### Question 5
What is the mean energy supply per capita?

*This function should return a single number.*

In [97]:
def answer_five():
    # YOUR CODE HERE
    Energy = pd.read_excel("assets/Energy Indicators.xls",usecols='C:F',
                           skiprows=[1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,17],
                          skipfooter=18,
                          names=['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable'])
    
    Energy["Country"] = Energy["Country"].replace("Republic of Korea", "South Korea")
    Energy["Country"] = Energy["Country"].replace("United States of America", "United States")
    Energy["Country"] = Energy["Country"].replace("United Kingdom of Great Britain and Northern Ireland", "United Kingdom")
    Energy["Country"] = Energy["Country"].replace("China, Hong Kong Special Administrative Region", "Hong Kong")
    
    #Energy["Energy Supply"] = Energy["Energy Supply"].replace("...",np.NaN)
    #Energy["Energy Supply"] = Energy["Energy Supply per Capita"].replace("...",np.NaN)
    #Energy["Energy Supply"] = Energy["% Renewable"].replace("...",np.NaN)
    #Energy['Country'] = Energy["Country"].replace(r"\(.*?\)", "",regex=True)
    #mean = Energy['Energy Supply per Capita'].nanmean()
    #mean = Energy['Energy Supply per Capita'].where(type(Energy['Energy Supply per Capita'])=='str')
    #for val in Energy['Energy Supply per Capita']:
     #   print(type(val))
        #rint(i)
    #print(mean)
    mean = pd.to_numeric(Energy['Energy Supply per Capita'],errors='coerce').mean()
    print(mean)
answer_five()

90.80269058295964

In [ ]:
# Cell for autograder.

### Question 6
What country has the maximum % Renewable and what is the percentage?

*This function should return a tuple with the name of the country and the percentage.*

In [106]:
def answer_six():
    # YOUR CODE HERE
    Energy = pd.read_excel("assets/Energy Indicators.xls",usecols='C:F',
                           skiprows=[1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,17],
                          skipfooter=18,
                          names=['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable'])
    
    maxs = Energy.where(Energy['% Renewable'] == Energy['% Renewable'].max()).dropna()
    display(Energy[Energy['% Renewable'] == Energy['% Renewable'].max()])
    print(maxs)
answer_six()

     Country Energy Supply Energy Supply per Capita  % Renewable
2    Albania           102                       35        100.0
24    Bhutan            63                       83        100.0
117  Lesotho            48                       23        100.0

     Country Energy Supply Energy Supply per Capita  % Renewable
2    Albania           102                       35        100.0
24    Bhutan            63                       83        100.0
117  Lesotho            48                       23        100.0

In [ ]:
assert type(answer_six()) == tuple, "Q6: You should return a tuple!"

assert type(answer_six()[0]) == str, "Q6: The first element in your result should be the name of the country!"

### Question 7
Create a new column that is the ratio of Self-Citations to Total Citations. 
What is the maximum value for this new column, and what country has the highest ratio?

*This function should return a tuple with the name of the country and the ratio.*

In [115]:
def answer_seven():
    # YOUR CODE HERE
    ScimEn = pd.read_excel("assets/scimagojr-3.xlsx")
    print(ScimEn)
    ratio = ScimEn['Self-citations']/ScimEn['Citations']
    #print(ScimEn.where(ScimEn['Citations']==np.NaN))
    print(ratio)
    ScimEn['ratio'] = ratio * 100
    display(ScimEn)
    #raise NotImplementedError()
answer_seven()

     Rank             Country  Documents  Citable documents  Citations  \
0       1               China     127050             126767     597237
1       2       United States      96661              94747     792274
2       3               Japan      30504              30287     223024
3       4      United Kingdom      20944              20357     206091
4       5  Russian Federation      18534              18301      34266
..    ...                 ...        ...                ...        ...
186   187              Guyana          1                  1          0
187   188    Christmas Island          1                  1          0
188   189             Reunion          1                  1          2
189   190         Saint Lucia          1                  1          0
190   191          Mauritania          1                  1          1

     Self-citations  Citations per document  H index
0            411683                    4.70      138
1            265436                    8.20      230
2             61554                    7.31      134
3             37874                    9.84      139
4             12422                    1.85       57
..              ...                     ...      ...
186               0                    0.00        0
187               0                    0.00        0
188               1                    2.00        1
189               0                    0.00        0
190               0                    1.00        1

[191 rows x 8 columns]
0      0.689313
1      0.335031
2      0.275997
3      0.183773
4      0.362517
         ...
186         NaN
187         NaN
188    0.500000
189         NaN
190    0.000000
Length: 191, dtype: float64

,Rank,Country,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,ratio
0,1,China,127050,126767,597237,411683,4.70,138,68.931262
1,2,United States,96661,94747,792274,265436,8.20,230,33.503056
2,3,Japan,30504,30287,223024,61554,7.31,134,27.599720
3,4,United Kingdom,20944,20357,206091,37874,9.84,139,18.377319
4,5,Russian Federation,18534,18301,34266,12422,1.85,57,36.251678
...,...,...,...,...,...,...,...,...,...
186,187,Guyana,1,1,0,0,0.00,0,NaN
187,188,Christmas Island,1,1,0,0,0.00,0,NaN
188,189,Reunion,1,1,2,1,2.00,1,50.000000
189,190,Saint Lucia,1,1,0,0,0.00,0,NaN
190,191,Mauritania,1,1,1,0,1.00,1,0.000000

In [ ]:
assert type(answer_seven()) == tuple, "Q7: You should return a tuple!"

assert type(answer_seven()[0]) == str, "Q7: The first element in your result should be the name of the country!"

### Question 8

Create a column that estimates the population using Energy Supply and Energy Supply per capita. 
What is the third most populous country according to this estimate?

*This function should return the name of the country*

In [ ]:
def answer_eight():
    # YOUR CODE HERE
    raise NotImplementedError()

In [ ]:
assert type(answer_eight()) == str, "Q8: You should return the name of the country!"

### Question 9
Create a column that estimates the number of citable documents per person. 
What is the correlation between the number of citable documents per capita and the energy supply per capita? Use the `.corr()` method, (Pearson's correlation).

*This function should return a single number.*

*(Optional: Use the built-in function `plot9()` to visualize the relationship between Energy Supply per Capita vs. Citable docs per Capita)*

In [6]:
def answer_nine():
    # YOUR CODE HERE
    one = answer_one()
    display(one)
    cit_per_pers = one['Citations']/one['Citations per document']
    
    one['citable docs per person'] = cit_per_pers
    cor = one[['citable docs per person','Energy Supply per Capita']].corr(method='pearson')
    print('cor')
    display(cor)
    display(cit_per_pers)
    #raise NotImplementedError()
answer_nine()
plot9()

Top15

,Country,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,2006.0,2007.0,...,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,Energy Supply,Energy Supply per Capita,% Renewable
0,China,1,127050,126767,597237,411683,4.70,138,3.992331e+12,4.559041e+12,...,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,NaN,NaN,NaN
1,United States,2,96661,94747,792274,265436,8.20,230,1.479230e+13,1.505540e+13,...,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,NaN,NaN,NaN
2,Japan,3,30504,30287,223024,61554,7.31,134,5.496542e+12,5.617036e+12,...,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,NaN,NaN,NaN
3,United Kingdom,4,20944,20357,206091,37874,9.84,139,2.419631e+12,2.482203e+12,...,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,NaN,NaN,NaN
4,Russian Federation,5,18534,18301,34266,12422,1.85,57,1.385793e+12,1.504071e+12,...,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,17.288680,214,17.288680
5,Canada,6,17899,17620,215003,40930,12.01,149,1.564469e+12,1.596740e+12,...,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12,61.945430,296,61.945430
6,Germany,7,17027,16831,140566,27426,8.26,126,3.332891e+12,3.441561e+12,...,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12,17.901530,165,17.901530
7,India,8,15005,14841,128763,37209,8.58,115,1.265894e+12,1.374865e+12,...,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,14.969080,26,14.969080
8,France,9,13153,12973,130632,28601,9.93,114,2.607840e+12,2.669424e+12,...,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12,NaN,NaN,NaN
9,South Korea,10,11983,11923,114675,22595,9.57,104,9.410199e+11,9.924316e+11,...,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12,2.279353,221,2.279353
10,Italy,11,10964,10794,111850,26661,10.20,106,2.202170e+12,2.234627e+12,...,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12,NaN,NaN,NaN
11,Spain,12,9428,9330,123336,23964,13.08,115,1.414823e+12,1.468146e+12,...,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12,NaN,NaN,NaN
12,Australia,14,8831,8725,90765,15606,10.28,107,1.021939e+12,1.060340e+12,...,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12,NaN,NaN,NaN
13,Brazil,15,8668,8596,60702,14396,7.00,86,1.845080e+12,1.957118e+12,...,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,69.648030,59,69.648030

,Country,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,2006.0,2007.0,...,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,Energy Supply,Energy Supply per Capita,% Renewable
0,China,1,127050,126767,597237,411683,4.70,138,3.992331e+12,4.559041e+12,...,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,NaN,NaN,NaN
1,United States,2,96661,94747,792274,265436,8.20,230,1.479230e+13,1.505540e+13,...,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,NaN,NaN,NaN
2,Japan,3,30504,30287,223024,61554,7.31,134,5.496542e+12,5.617036e+12,...,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,NaN,NaN,NaN
3,United Kingdom,4,20944,20357,206091,37874,9.84,139,2.419631e+12,2.482203e+12,...,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,NaN,NaN,NaN
4,Russian Federation,5,18534,18301,34266,12422,1.85,57,1.385793e+12,1.504071e+12,...,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,17.288680,214,17.288680
5,Canada,6,17899,17620,215003,40930,12.01,149,1.564469e+12,1.596740e+12,...,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12,61.945430,296,61.945430
6,Germany,7,17027,16831,140566,27426,8.26,126,3.332891e+12,3.441561e+12,...,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12,17.901530,165,17.901530
7,India,8,15005,14841,128763,37209,8.58,115,1.265894e+12,1.374865e+12,...,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,14.969080,26,14.969080
8,France,9,13153,12973,130632,28601,9.93,114,2.607840e+12,2.669424e+12,...,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12,NaN,NaN,NaN
9,South Korea,10,11983,11923,114675,22595,9.57,104,9.410199e+11,9.924316e+11,...,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12,2.279353,221,2.279353
10,Italy,11,10964,10794,111850,26661,10.20,106,2.202170e+12,2.234627e+12,...,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12,NaN,NaN,NaN
11,Spain,12,9428,9330,123336,23964,13.08,115,1.414823e+12,1.468146e+12,...,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12,NaN,NaN,NaN
12,Australia,14,8831,8725,90765,15606,10.28,107,1.021939e+12,1.060340e+12,...,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12,NaN,NaN,NaN
13,Brazil,15,8668,8596,60702,14396,7.00,86,1.845080e+12,1.957118e+12,...,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,69.648030,59,69.648030

cor

                         citable docs per person
citable docs per person                      1.0

0     127071.702128
1      96618.780488
2      30509.439124
3      20944.207317
4      18522.162162
5      17901.998335
6      17017.675545
7      15007.342657
8      13155.287009
9      11982.758621
10     10965.686275
11      9429.357798
12      8829.280156
13      8671.714286
dtype: float64

NameError: name 'plot9' is not defined

In [9]:
def plot9():
    import matplotlib as plt
    %matplotlib inline
    
    Top15 = answer_one()
    Top15['PopEst'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    Top15['Citable docs per Capita'] = Top15['Citable documents'] / Top15['PopEst']
    Top15.plot(x='Citable docs per Capita', y='Energy Supply per Capita', kind='scatter', xlim=[0, 0.0006])

In [ ]:
assert answer_nine() >= -1. and answer_nine() <= 1., "Q9: A valid correlation should between -1 to 1!"

### Question 10
Create a new column with a 1 if the country's % Renewable value is at or above the median for all countries in the top 15, and a 0 if the country's % Renewable value is below the median.

*This function should return a series named `HighRenew` whose index is the country name sorted in ascending order of rank.*

In [125]:
def answer_ten():
    # YOUR CODE HERE
    final = answer_one()
    median = final['% Renewable'].median()
    print(median)
    #for val in final:
     #   print(val['% Renewable'])
    HR = final['% Renewable'] > median
    HR = HR = HR.astype(int)
    final['HighRenew'] = HR
    print(final)
    #display(final)
    #raise NotImplementedError()
    return final
answer_ten()

,Rank,Country,Documents,Citable documents,Citations,Self-citations,Citations per document,H index
0,1,China,127050,126767,597237,411683,4.70,138
1,2,United States,96661,94747,792274,265436,8.20,230
2,3,Japan,30504,30287,223024,61554,7.31,134
3,4,United Kingdom,20944,20357,206091,37874,9.84,139
4,5,Russian Federation,18534,18301,34266,12422,1.85,57
5,6,Canada,17899,17620,215003,40930,12.01,149
6,7,Germany,17027,16831,140566,27426,8.26,126
7,8,India,15005,14841,128763,37209,8.58,115
8,9,France,13153,12973,130632,28601,9.93,114
9,10,South Korea,11983,11923,114675,22595,9.57,104
10,11,Italy,10964,10794,111850,26661,10.20,106
11,12,Spain,9428,9330,123336,23964,13.08,115
12,13,Iran,8896,8819,57470,19125,6.46,72
13,14,Australia,8831,8725,90765,15606,10.28,107
14,15,Brazil,8668,8596,60702,14396,7.00,86

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,2006.0,2007.0,2008.0,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0
Country,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2,96661,94747,792274,265436,8.20,230,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3,30504,30287,223024,61554,7.31,134,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,4,20944,20357,206091,37874,9.84,139,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,5,18534,18301,34266,12422,1.85,57,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
Canada,6,17899,17620,215003,40930,12.01,149,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
Germany,7,17027,16831,140566,27426,8.26,126,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
India,8,15005,14841,128763,37209,8.58,115,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
France,9,13153,12973,130632,28601,9.93,114,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
South Korea,10,11983,11923,114675,22595,9.57,104,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12
Italy,11,10964,10794,111850,26661,10.20,106,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
Spain,12,9428,9330,123336,23964,13.08,115,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
Australia,14,8831,8725,90765,15606,10.28,107,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,15,8668,8596,60702,14396,7.00,86,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12

17.595105
               Country  Rank  Documents  Citable documents  Citations  \
0                China     1     127050             126767     597237
1        United States     2      96661              94747     792274
2                Japan     3      30504              30287     223024
3       United Kingdom     4      20944              20357     206091
4   Russian Federation     5      18534              18301      34266
5               Canada     6      17899              17620     215003
6              Germany     7      17027              16831     140566
7                India     8      15005              14841     128763
8               France     9      13153              12973     130632
9          South Korea    10      11983              11923     114675
10               Italy    11      10964              10794     111850
11               Spain    12       9428               9330     123336
12           Australia    14       8831               8725      90765
13              Brazil    15       8668               8596      60702

    Self-citations  Citations per document  H index        2006.0  \
0           411683                    4.70      138  3.992331e+12
1           265436                    8.20      230  1.479230e+13
2            61554                    7.31      134  5.496542e+12
3            37874                    9.84      139  2.419631e+12
4            12422                    1.85       57  1.385793e+12
5            40930                   12.01      149  1.564469e+12
6            27426                    8.26      126  3.332891e+12
7            37209                    8.58      115  1.265894e+12
8            28601                    9.93      114  2.607840e+12
9            22595                    9.57      104  9.410199e+11
10           26661                   10.20      106  2.202170e+12
11           23964                   13.08      115  1.414823e+12
12           15606                   10.28      107  1.021939e+12
13           14396                    7.00       86  1.845080e+12

          2007.0  ...        2010.0        2011.0        2012.0        2013.0  \
0   4.559041e+12  ...  6.039659e+12  6.612490e+12  7.124978e+12  7.672448e+12
1   1.505540e+13  ...  1.496437e+13  1.520402e+13  1.554216e+13  1.577367e+13
2   5.617036e+12  ...  5.498718e+12  5.473738e+12  5.569102e+12  5.644659e+12
3   2.482203e+12  ...  2.403504e+12  2.450911e+12  2.479809e+12  2.533370e+12
4   1.504071e+12  ...  1.524917e+12  1.589943e+12  1.645876e+12  1.666934e+12
5   1.596740e+12  ...  1.613406e+12  1.664087e+12  1.693133e+12  1.730688e+12
6   3.441561e+12  ...  3.417298e+12  3.542371e+12  3.556724e+12  3.567317e+12
7   1.374865e+12  ...  1.708459e+12  1.821872e+12  1.924235e+12  2.051982e+12
8   2.669424e+12  ...  2.646995e+12  2.702032e+12  2.706968e+12  2.722567e+12
9   9.924316e+11  ...  1.094499e+12  1.134796e+12  1.160809e+12  1.194429e+12
10  2.234627e+12  ...  2.125185e+12  2.137439e+12  2.077184e+12  2.040871e+12
11  1.468146e+12  ...  1.431673e+12  1.417355e+12  1.380216e+12  1.357139e+12
12  1.060340e+12  ...  1.142251e+12  1.169431e+12  1.211913e+12  1.241484e+12
13  1.957118e+12  ...  2.208872e+12  2.295245e+12  2.339209e+12  2.409740e+12

          2014.0        2015.0  Energy Supply  Energy Supply per Capita  \
0   8.230121e+12  8.797999e+12            NaN                       NaN
1   1.615662e+13  1.654857e+13            NaN                       NaN
2   5.642884e+12  5.669563e+12            NaN                       NaN
3   2.605643e+12  2.666333e+12            NaN                       NaN
4   1.678709e+12  1.616149e+12      17.288680                       214
5   1.773486e+12  1.792609e+12      61.945430                       296
6   3.624386e+12  3.685556e+12      17.901530                       165
7   2.200617e+12  2.367206e+12      14.969080                        26
8   2.729632e+12  2.761185e+12            NaN                       NaN
9   1.234340e+12  1.266580e+12       2.279353                       221
10  2.033868e+12  2.049316e+12            NaN                       NaN
11  1.375605e+12  1.419821e+12            NaN                       NaN
12  1.272520e+12  1.301251e+12            NaN                       NaN
13  2.412231e+12  2.319423e+12      69.648030                        59

    % Renewable HighRenew
0           NaN         0
1           NaN         0
2           NaN         0
3           NaN         0
4     17.288680         0
5     61.945430         1
6     17.901530         1
7     14.969080         0
8           NaN         0
9      2.279353         0
10          NaN         0
11          NaN         0
12          NaN         0
13    69.648030         1

[14 rows x 22 columns]

In [ ]:
assert type(answer_ten()) == pd.Series, "Q10: You should return a Series!"

### Question 11
Use the following dictionary to group the Countries by Continent, then create a DataFrame that displays the sample size (the number of countries in each continent bin), and the sum, mean, and std deviation for the estimated population of each country.

```python
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}
```

*This function should return a DataFrame with index named Continent `['Asia', 'Australia', 'Europe', 'North America', 'South America']` and columns `['size', 'sum', 'mean', 'std']`*

In [55]:
def answer_eleven():
    # YOUR CODE HERE
    ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  #'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}
    
    final = answer_one()
    stats = pd.DataFrame(columns =['Continent','size', 'sum', 'mean', 'std'] ) 
    stats.set_index('Continent')
    final=final.set_index('Country')
    final['Est Pop'] = final['Energy Supply'] / final['Energy Supply per Capita']
    #stats = final.set_index('Country')
    #display(final)
    #final.set_index(ContinentDict.values())
    for key in ContinentDict:
        final.at[key,'Continent'] = ContinentDict[key]
    #final.agg({"Continent":ContinentDict})
    display(stats)
    #for Continent in  final['Continent'].unique():
    #    print(Continent)
        
    for group,frame in final.groupby(by='Continent'):
        stats.at[group,'sum'] = frame['Est Pop'].sum()
        #repeat this for the std, mean, and len
    display(stats)   
    #raise NotImplementedError()
answer_eleven()

Top15

,Country,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,2006.0,2007.0,...,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,Energy Supply,Energy Supply per Capita,% Renewable
0,China,1,127050,126767,597237,411683,4.70,138,3.992331e+12,4.559041e+12,...,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,NaN,NaN,NaN
1,United States,2,96661,94747,792274,265436,8.20,230,1.479230e+13,1.505540e+13,...,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,NaN,NaN,NaN
2,Japan,3,30504,30287,223024,61554,7.31,134,5.496542e+12,5.617036e+12,...,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,NaN,NaN,NaN
3,United Kingdom,4,20944,20357,206091,37874,9.84,139,2.419631e+12,2.482203e+12,...,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,NaN,NaN,NaN
4,Russian Federation,5,18534,18301,34266,12422,1.85,57,1.385793e+12,1.504071e+12,...,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,17.288680,214,17.288680
5,Canada,6,17899,17620,215003,40930,12.01,149,1.564469e+12,1.596740e+12,...,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12,61.945430,296,61.945430
6,Germany,7,17027,16831,140566,27426,8.26,126,3.332891e+12,3.441561e+12,...,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12,17.901530,165,17.901530
7,India,8,15005,14841,128763,37209,8.58,115,1.265894e+12,1.374865e+12,...,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,14.969080,26,14.969080
8,France,9,13153,12973,130632,28601,9.93,114,2.607840e+12,2.669424e+12,...,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12,NaN,NaN,NaN
9,South Korea,10,11983,11923,114675,22595,9.57,104,9.410199e+11,9.924316e+11,...,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12,2.279353,221,2.279353
10,Italy,11,10964,10794,111850,26661,10.20,106,2.202170e+12,2.234627e+12,...,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12,NaN,NaN,NaN
11,Spain,12,9428,9330,123336,23964,13.08,115,1.414823e+12,1.468146e+12,...,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12,NaN,NaN,NaN
12,Australia,14,8831,8725,90765,15606,10.28,107,1.021939e+12,1.060340e+12,...,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12,NaN,NaN,NaN
13,Brazil,15,8668,8596,60702,14396,7.00,86,1.845080e+12,1.957118e+12,...,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,69.648030,59,69.648030

Empty DataFrame
Columns: [Continent, size, sum, mean, std]
Index: []

              Continent size       sum mean  std
Asia                NaN  NaN  0.586048  NaN  NaN
Australia           NaN  NaN         0  NaN  NaN
Europe              NaN  NaN  0.189282  NaN  NaN
North America       NaN  NaN  0.209275  NaN  NaN
South America       NaN  NaN  1.180475  NaN  NaN

In [ ]:
assert type(answer_eleven()) == pd.DataFrame, "Q11: You should return a DataFrame!"

assert answer_eleven().shape[0] == 5, "Q11: Wrong row numbers!"

assert answer_eleven().shape[1] == 4, "Q11: Wrong column numbers!"

### Question 12
Cut % Renewable into 5 bins. Group Top15 by the Continent, as well as these new % Renewable bins. How many countries are in each of these groups?

*This function should return a Series with a MultiIndex of `Continent`, then the bins for `% Renewable`. Do not include groups with no countries.*

In [71]:
def answer_twelve():
    # YOUR CODE HERE
    ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  #'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}
    
    final = answer_one()
    
    final["bins"] = pd.cut(final['% Renewable'],5)
    for key in ContinentDict:
        final.at[key,'Continent'] = ContinentDict[key]
    x=final.groupby(['Continent','bins']).size()
    display(x.head(100))
    #display(final)
    #raise NotImplementedError()
answer_twelve()

Top15

,Country,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,2006.0,2007.0,...,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,Energy Supply,Energy Supply per Capita,% Renewable
0,China,1,127050,126767,597237,411683,4.70,138,3.992331e+12,4.559041e+12,...,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,NaN,NaN,NaN
1,United States,2,96661,94747,792274,265436,8.20,230,1.479230e+13,1.505540e+13,...,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,NaN,NaN,NaN
2,Japan,3,30504,30287,223024,61554,7.31,134,5.496542e+12,5.617036e+12,...,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,NaN,NaN,NaN
3,United Kingdom,4,20944,20357,206091,37874,9.84,139,2.419631e+12,2.482203e+12,...,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,NaN,NaN,NaN
4,Russian Federation,5,18534,18301,34266,12422,1.85,57,1.385793e+12,1.504071e+12,...,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,17.288680,214,17.288680
5,Canada,6,17899,17620,215003,40930,12.01,149,1.564469e+12,1.596740e+12,...,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12,61.945430,296,61.945430
6,Germany,7,17027,16831,140566,27426,8.26,126,3.332891e+12,3.441561e+12,...,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12,17.901530,165,17.901530
7,India,8,15005,14841,128763,37209,8.58,115,1.265894e+12,1.374865e+12,...,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,14.969080,26,14.969080
8,France,9,13153,12973,130632,28601,9.93,114,2.607840e+12,2.669424e+12,...,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12,NaN,NaN,NaN
9,South Korea,10,11983,11923,114675,22595,9.57,104,9.410199e+11,9.924316e+11,...,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12,2.279353,221,2.279353
10,Italy,11,10964,10794,111850,26661,10.20,106,2.202170e+12,2.234627e+12,...,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12,NaN,NaN,NaN
11,Spain,12,9428,9330,123336,23964,13.08,115,1.414823e+12,1.468146e+12,...,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12,NaN,NaN,NaN
12,Australia,14,8831,8725,90765,15606,10.28,107,1.021939e+12,1.060340e+12,...,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12,NaN,NaN,NaN
13,Brazil,15,8668,8596,60702,14396,7.00,86,1.845080e+12,1.957118e+12,...,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,69.648030,59,69.648030

Continent      bins
Asia           (2.212, 15.753]     0
               (15.753, 29.227]    0
               (29.227, 42.701]    0
               (42.701, 56.174]    0
               (56.174, 69.648]    0
Australia      (2.212, 15.753]     0
               (15.753, 29.227]    0
               (29.227, 42.701]    0
               (42.701, 56.174]    0
               (56.174, 69.648]    0
Europe         (2.212, 15.753]     0
               (15.753, 29.227]    0
               (29.227, 42.701]    0
               (42.701, 56.174]    0
               (56.174, 69.648]    0
North America  (2.212, 15.753]     0
               (15.753, 29.227]    0
               (29.227, 42.701]    0
               (42.701, 56.174]    0
               (56.174, 69.648]    0
South America  (2.212, 15.753]     0
               (15.753, 29.227]    0
               (29.227, 42.701]    0
               (42.701, 56.174]    0
               (56.174, 69.648]    0
dtype: int64

In [ ]:
assert type(answer_twelve()) == pd.Series, "Q12: You should return a Series!"

assert len(answer_twelve()) == 9, "Q12: Wrong result numbers!"

### Question 13
Convert the Population Estimate series to a string with thousands separator (using commas). Use all significant digits (do not round the results).

e.g. 12345678.90 -> 12,345,678.90

*This function should return a series `PopEst` whose index is the country name and whose values are the population estimate string*

In [57]:
def answer_thirteen():
    # YOUR CODE HERE
    
    #raise NotImplementedError()
answer_thirteen()

Top15

,Country,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,2006.0,2007.0,...,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,Energy Supply,Energy Supply per Capita,% Renewable
0,China,1,127050,126767,597237,411683,4.70,138,3.992331e+12,4.559041e+12,...,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,NaN,NaN,NaN
1,United States,2,96661,94747,792274,265436,8.20,230,1.479230e+13,1.505540e+13,...,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,NaN,NaN,NaN
2,Japan,3,30504,30287,223024,61554,7.31,134,5.496542e+12,5.617036e+12,...,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,NaN,NaN,NaN
3,United Kingdom,4,20944,20357,206091,37874,9.84,139,2.419631e+12,2.482203e+12,...,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,NaN,NaN,NaN
4,Russian Federation,5,18534,18301,34266,12422,1.85,57,1.385793e+12,1.504071e+12,...,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,17.288680,214,17.288680
5,Canada,6,17899,17620,215003,40930,12.01,149,1.564469e+12,1.596740e+12,...,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12,61.945430,296,61.945430
6,Germany,7,17027,16831,140566,27426,8.26,126,3.332891e+12,3.441561e+12,...,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12,17.901530,165,17.901530
7,India,8,15005,14841,128763,37209,8.58,115,1.265894e+12,1.374865e+12,...,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,14.969080,26,14.969080
8,France,9,13153,12973,130632,28601,9.93,114,2.607840e+12,2.669424e+12,...,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12,NaN,NaN,NaN
9,South Korea,10,11983,11923,114675,22595,9.57,104,9.410199e+11,9.924316e+11,...,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12,2.279353,221,2.279353
10,Italy,11,10964,10794,111850,26661,10.20,106,2.202170e+12,2.234627e+12,...,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12,NaN,NaN,NaN
11,Spain,12,9428,9330,123336,23964,13.08,115,1.414823e+12,1.468146e+12,...,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12,NaN,NaN,NaN
12,Australia,14,8831,8725,90765,15606,10.28,107,1.021939e+12,1.060340e+12,...,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12,NaN,NaN,NaN
13,Brazil,15,8668,8596,60702,14396,7.00,86,1.845080e+12,1.957118e+12,...,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,69.648030,59,69.648030

,Country,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,2006.0,2007.0,...,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,Energy Supply,Energy Supply per Capita,% Renewable,bins
0,China,1,127050,126767,597237,411683,4.70,138,3.992331e+12,4.559041e+12,...,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,NaN,NaN,NaN,NaN
1,United States,2,96661,94747,792274,265436,8.20,230,1.479230e+13,1.505540e+13,...,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,NaN,NaN,NaN,NaN
2,Japan,3,30504,30287,223024,61554,7.31,134,5.496542e+12,5.617036e+12,...,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,NaN,NaN,NaN,NaN
3,United Kingdom,4,20944,20357,206091,37874,9.84,139,2.419631e+12,2.482203e+12,...,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,NaN,NaN,NaN,NaN
4,Russian Federation,5,18534,18301,34266,12422,1.85,57,1.385793e+12,1.504071e+12,...,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,17.288680,214,17.288680,"(15.753, 29.227]"
5,Canada,6,17899,17620,215003,40930,12.01,149,1.564469e+12,1.596740e+12,...,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12,61.945430,296,61.945430,"(56.174, 69.648]"
6,Germany,7,17027,16831,140566,27426,8.26,126,3.332891e+12,3.441561e+12,...,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12,17.901530,165,17.901530,"(15.753, 29.227]"
7,India,8,15005,14841,128763,37209,8.58,115,1.265894e+12,1.374865e+12,...,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,14.969080,26,14.969080,"(2.212, 15.753]"
8,France,9,13153,12973,130632,28601,9.93,114,2.607840e+12,2.669424e+12,...,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12,NaN,NaN,NaN,NaN
9,South Korea,10,11983,11923,114675,22595,9.57,104,9.410199e+11,9.924316e+11,...,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12,2.279353,221,2.279353,"(2.212, 15.753]"
10,Italy,11,10964,10794,111850,26661,10.20,106,2.202170e+12,2.234627e+12,...,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12,NaN,NaN,NaN,NaN
11,Spain,12,9428,9330,123336,23964,13.08,115,1.414823e+12,1.468146e+12,...,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12,NaN,NaN,NaN,NaN
12,Australia,14,8831,8725,90765,15606,10.28,107,1.021939e+12,1.060340e+12,...,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12,NaN,NaN,NaN,NaN
13,Brazil,15,8668,8596,60702,14396,7.00,86,1.845080e+12,1.957118e+12,...,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,69.648030,59,69.648030,"(56.174, 69.648]"

In [ ]:
assert type(answer_thirteen()) == pd.Series, "Q13: You should return a Series!"

assert len(answer_thirteen()) == 15, "Q13: Wrong result numbers!"

### Optional

Use the built in function `plot_optional()` to see an example visualization.

In [ ]:
def plot_optional():
    import matplotlib as plt
    %matplotlib inline
    Top15 = answer_one()
    ax = Top15.plot(x='Rank', y='% Renewable', kind='scatter', 
                    c=['#e41a1c','#377eb8','#e41a1c','#4daf4a','#4daf4a','#377eb8','#4daf4a','#e41a1c',
                       '#4daf4a','#e41a1c','#4daf4a','#4daf4a','#e41a1c','#dede00','#ff7f00'], 
                    xticks=range(1,16), s=6*Top15['2014']/10**10, alpha=.75, figsize=[16,6]);

    for i, txt in enumerate(Top15.index):
        ax.annotate(txt, [Top15['Rank'][i], Top15['% Renewable'][i]], ha='center')

    print("This is an example of a visualization that can be created to help understand the data. \
This is a bubble chart showing % Renewable vs. Rank. The size of the bubble corresponds to the countries' \
2014 GDP, and the color corresponds to the continent.")